<?php

return [
    'months'=>[
        0=>[
            'protein'=>220,
            'fat'=>80,
            'carbohydrates'=>225,
            'energy'=>2500,
        ]
    ],
    'weekdays'=>[
        0=>[
            'protein'=>1,
            'fat'=>1,
            'carbohydrates'=>1,
            'energy'=>1,
        ],
        1=>[
            'protein'=>1.2,
            'fat'=>1.4,
            'carbohydrates'=>1.5,
            'energy'=>1.36,
        ],
        2=>[
            'protein'=>1.1,
            'fat'=>1.2,
            'carbohydrates'=>1.3,
            'energy'=>1.2,
        ],
        4=>[
            'protein'=>1,
            'fat'=>0.9,
            'carbohydrates'=>0.85,
            'energy'=>0.97,
        ],
        5=>[
            'protein'=>1.05,
            'fat'=>0.8,
            'carbohydrates'=>0.8,
            'energy'=>0.89,
        ],
        6=>[
            'protein'=>1.1,
            'fat'=>0.75,
            'carbohydrates'=>0.7,
            'energy'=>0.85,
        ],
        7=>[
            'protein'=>1.1,
            'fat'=>0.6,
            'carbohydrates'=>0.6,
            'energy'=>0.78,
        ],
    ],
];